### ISSUE TITLE
What is the Lotus Notes password for an offline NFS

### ISSUE THREAD

**Issue by alfnsMrtnz** [adb014/nsf2x#11]
Hi there,

I'm not that savvy on Lotus Notes systems, but I'm trying to convert a NSF file to PST, and when it comes to the password for Lotus Notes in nsf2x I don't really know what to use, I don't have the accounts owner's password, would that be the one? on the other hand I stablished a password in the User security settings on Lotues Notes client, but that doesn't work on nsf2x.

Could you give me a hand on this?

**Comment by adb014** [comment]
The password is the same as used to acces the NSF file with Lotus Notes itself

D.
