### ISSUE TITLE
Error to connect server lotus

### ISSUE THREAD

**Issue by mlchaume** [adb014/nsf2x#18]
Hello,
I get an error with your tool... 
Connect to server fail..

ERREUR : Erreur de connexion à Lotus !
ERREUR : Exception (-2147221164, 'Classe non enregistrée', None, None) :
ERREUR : Vérifier le mot de passe de Notes et que l'architecture de NSF2X et Notes sont identique

however, Password is correct .

I've installed an outlook (office 2013) and I have admin console and lotus note on this server.

I need your help . Thank you very much

Regards

**Comment by adb014** [comment]
You are probably using the wrong version of NSF2X. The version must match the bitness of the version of Lotus. X86 for a 32bit install of Lotus and AMD64 for a 64bit version of Lotus. Closing as this is a known issue. If the problem persists after changing the version of NSF2X installed, reopen the report

D.
