### ISSUE TITLE
Exception in Tkinter callback

### ISSUE THREAD

**Issue by wwender** [adb014/nsf2x#3]
First thanks for providing nsf2x 👍 

I use nsf2x in the latest version(1.3.2) in a complete 32bit setup. I have an issue with one database containing about 100k Messages. After about 25k Messages I get the following exception:

Exception in Tkinter callback
Traceback (most recent call last):
  File "nsf2x.py", line 894, in realConvert
  File "<COMObject GetNextDocument>", line 2, in GetMIMEEntity
  File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\win32com\client\dynamic.py", line 287, in _ApplyTypes_
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'NotesDocument', 'Notes error: Invalid or missing RFC822 header name.', None, 0, -2147217504), None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\tkinter\__init__.py", line 1538, in __call__
  File "nsf2x.py", line 591, in doConvert
  File "nsf2x.py", line 655, in doConvertDirectory
  File "nsf2x.py", line 972, in realConvert
TypeError: unlink: can't specify None for path argument

**Comment by adb014** [comment]
For the missing RFC822 error there is not much I can do as the message itself seems to be corrupted. However, the RFC822 error shouldn't make NSF2X quit the conversion, rather than jsut skip the corrupt message. The trivial fix is to replace

```python
try:
    os.remove(eml)
except OSError:
    pass
```
around line 972 with

```python
try:
    os.remove(eml)
except (OSError, TypeError):
    pass
```

At the time of the first except the path to the eml file doexn't exist. I'll make a 1.3.3 release soon and put it on the site

**Comment by adb014** [comment]
Ok I fixed it slightly differently than the above so as not to enlarge too much the exceptions that are skipped, and have uploaded a v1.3.3. Give me feedback if the problem is fixed and I'll close this issue

David

**Comment by wwender** [comment]
Thanks. I will test it. 
Wim

**Comment by wwender** [comment]
It works (documents with exceptions are skipped)!

**Comment by adb014** [comment]
Ok, so closing this bug
