### ISSUE TITLE
Error while open session

### ISSUE THREAD

**Issue by feeling001** [adb014/nsf2x#5]
Hello, I have the following error while nsf2x open the session.

My setup:
 - Windows 7 x64
 - Lotus notes 8.5.3 x32
 - nsf2x 1.3.3. x86 (so the 32bit version)

I open nsf2x, then enter my nodes id password, click "Ouvrir la session" and nothing happends, even 5 minutes later.

After I close the converter, I get this in the log file :

`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\tkinter\__init__.py", line 1538, in __call__
    return self.func(*args)
  File "nsf2x.py", line 617, in doConvert
  File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\win32com\client\dynamic.py", line 527, in __getattr__
    raise AttributeError("%s.%s" % (self._username_, attr))
AttributeError: Lotus.NotesSession.Initialize
`
After seen this error, I have installed winpython 32bit (same version, in the same location) without error.

Any Idea ? Sinon on peut le faire en français aussi ...

Regards.

**Comment by adb014** [comment]
If you have WinPython installed can you try the following lines in Sypder

    import win32com.client
    Lotus = win32com.client.Dispatch(r'Lotus.NotesSession')
    Lotus.Initialize('YOUR_NOTES_PASSWORD_HERE')

It seems to me that the COM interface to Notes on your machine is not making the "Initialize" attribute visible which is just weird as I have exactly the same version of Lotus. Maybe with the above code you'll see better debugging information. Can you tell me the errors messages for the above.

Eventually it might be possible de export the COM binds to the Notes dll with makebind and use static rather than dynamic binding, but that always seemed messy to me.

D.

Sur github c'est mieux de faire en anglais

**Comment by adb014** [comment]
BTW you can test static dispatching with code like

    import win32com.client
    dispatch = win32com.client.gencache.EnsureDispatch 
    Lotus =dispatch(r'Lotus.NotesSession')
    Lotus.Initialize('YOUR_NOTES_PASSWORD_HERE')

Though the last line might need to be replace with

    Lotus.initialize('YOUR_NOTES_PASSWORD_HERE')

if I understanding the case sensitive nature of python static bindings.

D.

**Comment by feeling001** [comment]
With this code:
```
import win32com.client
Lotus = win32com.client.Dispatch(r'Lotus.NotesSession')
Lotus.Initialize('YOUR_NOTES_PASSWORD_HERE')
```
I get the following error :
```
runfile('C:/Logiciel/WinPython-32bit-3.4.4.4Qt5/settings/.spyder-py3/temp.py', wdir='C:/Logiciel/WinPython-32bit-3.4.4.4Qt5/settings/.spyder-py3')
Traceback (most recent call last):

  File "<ipython-input-5-13a766fdccfa>", line 1, in <module>
    runfile('C:/Logiciel/WinPython-32bit-3.4.4.4Qt5/settings/.spyder-py3/temp.py', wdir='C:/Logiciel/WinPython-32bit-3.4.4.4Qt5/settings/.spyder-py3')

  File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 845, in runfile
    execfile(filename, namespace)

  File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 103, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Logiciel/WinPython-32bit-3.4.4.4Qt5/settings/.spyder-py3/temp.py", line 10, in <module>
    Lotus.Initialize('laul0tus1')

  File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\win32com\client\dynamic.py", line 527, in __getattr__
    raise AttributeError("%s.%s" % (self._username_, attr))

AttributeError: Lotus.NotesSession.Initialize
```

for the second code, the case nature do not change the output (same behavior)

```
runfile('C:/Logiciel/WinPython-32bit-3.4.4.4Qt5/settings/.spyder-py3/temp.py', wdir='C:/Logiciel/WinPython-32bit-3.4.4.4Qt5/settings/.spyder-py3')
Traceback (most recent call last):

  File "<ipython-input-10-13a766fdccfa>", line 1, in <module>
    runfile('C:/Logiciel/WinPython-32bit-3.4.4.4Qt5/settings/.spyder-py3/temp.py', wdir='C:/Logiciel/WinPython-32bit-3.4.4.4Qt5/settings/.spyder-py3')

  File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 845, in runfile
    execfile(filename, namespace)

  File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 103, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Logiciel/WinPython-32bit-3.4.4.4Qt5/settings/.spyder-py3/temp.py", line 10, in <module>
    Lotus =dispatch(r'Lotus.NotesSession')

  File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\win32com\client\gencache.py", line 547, in EnsureDispatch
    raise TypeError("This COM object can not automate the makepy process - please run makepy manually for this object")

TypeError: This COM object can not automate the makepy process - please run makepy manually for this object
```
I've no idea about what makepy is ...

regards,
Laurent.

**Comment by adb014** [comment]
Before analysing the errors, I'd like to point out that your cut and paste of the errors contains your password.. You might like to change tit after having posted it to the internet ;-)

D.

**Comment by adb014** [comment]
I still don't understand what is happenning from the error messages, so I propose to unroll the static dispatch code and see where its failing

    import win32com.client
    import pywintypes
    disp = win32com.client.Dispatch(r'Lotus.NotesSession')
    mod1 = win32com.client.gencache.EnsureModule(pywintypes.IID('{29131520-2EED-1069-BF5D-00DD011186B7}'), 0, 1, 2, 1)
    mod2 = win32com.client.gencache.GetModuleForCLSID(pywintypes.IID('{29131578-2EED-1069-BF5D-00DD011186B7}'))
    disp_class = win32com.client.CLSIDToClass.GetClass('{29131578-2EED-1069-BF5D-00DD011186B7}')
    Lotus = disp_class(disp._oleobj_)
    Lotus.Initialize('YOUR_NOTES_PASSWORD_HERE')

By hardcoding the CLSID and IID of Lotus Notes  I'm hoping that the static mapping will work correctly.

D.

**Comment by feeling001** [comment]
I've not checked enough carefully the output of the Traceback, ....
I changed my password and edited my post on github. (and slapped myself,
shame on me !)

Therefore, .... I've run spyder with the static mapping method without
success.

runfile('C:/Logiciel/WinPython-32bit-3.4.4.4Qt5/settings/.spyder-py3/temp.py',
wdir='C:/Logiciel/WinPython-32bit-3.4.4.4Qt5/settings/.spyder-py3')
Traceback (most recent call last):

  File "<ipython-input-14-13a766fdccfa>", line 1, in <module>

runfile('C:/Logiciel/WinPython-32bit-3.4.4.4Qt5/settings/.spyder-py3/temp.py',
wdir='C:/Logiciel/WinPython-32bit-3.4.4.4Qt5/settings/.spyder-py3')

  File
"C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py",
line 845, in runfile
    execfile(filename, namespace)

  File
"C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py",
line 103, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File
"C:/Logiciel/WinPython-32bit-3.4.4.4Qt5/settings/.spyder-py3/temp.py", line
13, in <module>
    disp_class =
win32com.client.CLSIDToClass.GetClass('{29131578-2EED-1069-BF5D-00DD011186B7}')

  File
"C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\win32com\client\CLSIDToClass.py",
line 46, in GetClass
    return mapCLSIDToClass[clsid]

KeyError: '{29131578-2EED-1069-BF5D-00DD011186B7}'

Is there anything I can do at Notes side to ensure that the key is correct ?

**Comment by adb014** [comment]
Ok, so it seems that the registry entry for Lotus.NotesSession on your machine is messed up at it is giving the wrong CLSID. Maybe you have an addon to Lotus that is messing it up and pointing the COM interface to the wrong DLL. The "Lotus.NotesSession" CLSID in the registry should have an attribute InprocServer32 that points to the DLL dlsxbe.dll. You can check by searching in the registry for "Lotus.NotesSession" using regedit.

Before assuming the above, note that I extracted the CLSID above from the Python win32com object on my system. My registry tells me the CLSID is something different, so try the static mapping with 

    import win32com.client
    import pywintypes
    disp = win32com.client.Dispatch(r'Lotus.NotesSession')
    mod1 = win32com.client.gencache.EnsureModule(pywintypes.IID('{29131520-2EED-1069-BF5D-00DD011186B7}'), 0, 1, 2, 1)
    mod2 = win32com.client.gencache.GetModuleForCLSID(pywintypes.IID('{29131539-2EED-1069-BF5D-00DD011186B7}'))
    disp_class = win32com.client.CLSIDToClass.GetClass('{29131539-2EED-1069-BF5D-00DD011186B7}')
    Lotus = disp_class(disp._oleobj_)
    Lotus.Initialize('YOUR_NOTES_PASSWORD_HERE')

Note the slightly different value for CLSID. If this new code works, I can fix the problem in NSF2X, if it doen't I suspect you'll need to reinstall Notes to fix the registry.

D.

**Comment by feeling001** [comment]
I got the same KeyError.

KeyError: '{29131539-2EED-1069-BF5D-00DD011186B7}'

How did you extract the CLSID ? I've search any *NotesSession in the
windows registry without any success. I have not really the opportunity to
re-deploy Lotus Notes while it is a compagny laptop.

regards.

**Comment by adb014** [comment]
The Lotus.NotesSession value for a 32bit Lotus on a 64bit Machine is in the registery location

    HKLM/SOFTWARE/Wow6432Node/Classes/CLSID/{29131539-2EED-1069-BF5D-00DD011186B7}

on my machine. With the attributes InprocServer32, ProgID, TYpeLib and VersionIndependentProgID. So you don't have these values on your machine its seems your employer disabled the COM interface to Lotus. If you can can't reinstall Lotus I see two possible solutions

1.  Patch the registry as a UAC user with the commands

`
    reg ADD HKLM\SOFTWARE\Wow6432Node\Classes\CLSID\{29131539-2EED-1069-BF5D-00DD011186B7} /t REG_SZ /d "Lotus Domino Session"
    reg ADD HKLM\SOFTWARE\Wow6432Node\Classes\CLSID\{29131539-2EED-1069-BF5D-00DD011186B7}\InprocServer32 /t REG_SZ /d "c:\Program Files (86)\Notes\nlsxbe.dll"
    reg ADD HKLM\SOFTWARE\Wow6432Node\Classes\CLSID\{29131539-2EED-1069-BF5D-00DD011186B7}\InprocServer32 /t REG_SZ /v "ThreadingModel" /d "Both"
    reg ADD HKLM\SOFTWARE\Wow6432Node\Classes\CLSID\{29131539-2EED-1069-BF5D-00DD011186B7}\ProgID /t REG_SZ /d "Lotus.NotesSession.7.0"
    reg ADD HKLM\SOFTWARE\Wow6432Node\Classes\CLSID\{29131539-2EED-1069-BF5D-00DD011186B7}\TypeLib /t REG_SZ /d "{29131520-2EED-1069-BF5D-00DD011186B7}"
    reg ADD HKLM\SOFTWARE\Wow6432Node\Classes\CLSID\{29131539-2EED-1069-BF5D-00DD011186B7}\VersionIndependentProgID /t REG_SZ /d "Lotus.NotesSession"
`

With adjustments for the path to your version of nslxbe.dll. I haven't checked this so use with care and check the results with regedit.

2. Get me to try an use python ctypes.windll to interface to nnotes.dll rather than via the COM interface within NSF2X. This is frankly quite messy as the C API to nnotes.dll and the COM API are completely different. You're basically asking me to rewrite NSF2X for what to me seem to be a bug in your installation, even if it was your employer who disabled the COM interface to Notes on your machine, probably for security reasons. So I'd prefer that you patch your registry if you can't reinstall Notes.

David

**Comment by feeling001** [comment]
I confirm that you provided the right CLSID:

[image: Inline images 1]


I try to understand why I get this "KeyError".
Regards,

**Comment by feeling001** [comment]
I have the same registery parameters than your's. (except the installation
path).

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Classes\CLSID\{29131539-2EED-1069-BF5D-00DD011186B7}]
@="Lotus Domino Session"

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Classes\CLSID\{29131539-2EED-1069-BF5D-00DD011186B7}\InprocServer32]
@="C:\\Notes\\nlsxbe.dll"
"ThreadingModel"="Both"

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Classes\CLSID\{29131539-2EED-1069-BF5D-00DD011186B7}\ProgID]
@="Lotus.NotesSession.7.0"

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Classes\CLSID\{29131539-2EED-1069-BF5D-00DD011186B7}\TypeLib]
@="{29131520-2EED-1069-BF5D-00DD011186B7}"

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Classes\CLSID\{29131539-2EED-1069-BF5D-00DD011186B7}\VersionIndependentProgID]
@="Lotus.NotesSession"


There is no "COM port" defined , this is probably the root cause of
everything ... and I can't do anything about this.

[image: Inline images 1]

I was only trying to convert my nsf database to mbox or pst format to keep
my archives.

regards.

**Comment by adb014** [comment]
The inline images didn't seem to get sent, can you send them offline to my email address on the frontpage to NSF2X ?

So you do have the right registry settings. What do you mean by "no COM port" ? There is nothing wrong with you registry settings. Do you means that COM is entirely disabled using dcomcfng ? If so, use dcomcfng to turn it back on. See [http://www-01.ibm.com/support/docview.wss?uid=swg21681046](url)

D.

**Comment by feeling001** [comment]
I'll try a fresh install of lotus notes in a fresh virtual machine,

the corporate setup seems to be crappy.

regards.

**Comment by feeling001** [comment]
Hello,

I've done a fresh install of lotus notes in a virtualbox vm, imported my
notes /Data, ... and it works .... My corporate setup is probably too much
"tweaked".

Thanks for your help.

Laurent.

**Comment by adb014** [comment]
It would be nice to understand why it didn't work. But it seems that your company turns off COM with dcomcnfg completely. As you've found a solution and we have a probable explanation, I'm closing this bug

D.

**Comment by feeling001** [comment]
Hello,

I will try to understand why it didn't work.

I can't do anything with dcomcnfg because dcomcnfg can't create the snap-in
with our policies ...

regards.
