### ISSUE TITLE
About calendar

### ISSUE THREAD

**Issue by sgseb1402** [adb014/nsf2x#6]
Hello, 

I am working on a project to change lotus Note domino to exchange (office 365).
I see your work about nsf2x ; who is a very good job ! :- )

I try the tools today and convert a copy of my mailbox from .nsf to .pst with success (inbox, structure and sent item). No error on the converter process

But I have a problem with calendar; not present on the .pst
Can you give me some information about this point please ?

I am using Outlook 2013 x86 and lotus nots 9.

Regards,

**Comment by adb014** [comment]
At the moment NSF2X doesn’t handle calendars. They are mush harder to handle for the following reasons:

- Lotus does give an easy means to export them like for mails to EML This means we have to try and get Lotus to export to the calendar to mime and deal with the conversion of Lotus mail addresses to inet addresses and dates
- The ICS format doesn’t give an easy means to include embedded attachements, though with conversion NSF directly to PST it should be possible
- The calendar rucurence rules between Lotus and outlook are completely different so special treatment is needed for repeated events

Too much work to do this for me at this time


D.

**Comment by adb014** [comment]
I'm closing this issue as I'm not going to be fixing it in the short term
