### ISSUE TITLE
Error Creating PST

### ISSUE THREAD

**Issue by Dilbertdog** [adb014/nsf2x#8]
Hi, all working well to create EML files from NSF, but getting following error when making PST which causes EML's to be deleted. Any thoughts ? Running as Admin with Outlook 2013 open.

INFO : Starting importation of EML files into PST file
ERROR : Helper process return the error code (255)
ERROR : Traceback (most recent call last):
ERROR :   File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
ERROR : pywintypes.com_error: (-2147221021, 'Operation unavailable', None, None)
ERROR : 
ERROR : During handling of the above exception, another exception occurred:
ERROR : 
ERROR : Traceback (most recent call last):
ERROR :   File "eml2pst.py", line 46, in <module>
ERROR :   File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
ERROR :   File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
ERROR :   File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
ERROR : pywintypes.com_error: (-2146959355, 'Server execution failed', None, None)
ERROR : Importation of EML files into PST is incomplete
INFO : Removing temporary EML files

**Comment by adb014** [comment]
This like all of the open issues on this bug tracker are associated with the detection of "ClickToRun" (AKA Office365) versions of Office and the patching of the registry. Can you please serach the registry for the word "Office" in regedit and tell me the values you have. With this information I might be able to fix the issue. 

I don't have a ClickToRun installation and can't debug it myself.

D.

**Comment by Dilbertdog** [comment]
Hi David, thanks for the reply :-) really appreciated and great that I can do the EML's - now just PST instead.
I've looked at the microsoft site to see how I check for click to run for outlook by looking for the existence of HKEY_LOCAL_MACHINE\Software\Microsoft\Office\15.0\Common\InstallRoot\Virtual\VirtualOutlook which was not found in the registry.
The os is windows 64bit but using a 32bit notes client (8.5.3) and nsf2x happily converts to eml.
The version of outlook / office I have is Office 2013 Professional Plus 64bit 
I am therefore using nsfx 32bit for the conversion. Setting encryption to none and yes to helper.
What I have noticed is my patch level on outlook 2013 is old so I will update it first to the most recent and try again - then let you know the results
BR
Rob

**Comment by Dilbertdog** [comment]
Hi, okay Office updated to latest patch level (needed to add a new key to Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\15.0\ClickToRun\Configuration to set the url to enable updates to run).. Ran nsf2x as admin. Same error as above. 
Not sure which bit of registry you would like as searching office in regedit brings up many entries.
Very happy to provide as much info as I can to get this fixed !
BR
Rob

**Comment by Dilbertdog** [comment]
Update for you in case helpful - have managed to get everything to work following a process of trial and error - the following was needed in this case:
- Installed Office 2016
- Paused Kaspersky protection (and disabled network - for security !!)
- Open Lotus Notes and keep in background
- Don't open Outlook
- Set the options as follows: Re-encryption - None, Error logging - Infinite. Helper - Yes

And BINGO EML's created and automatically converted into PST

**Comment by adb014** [comment]
The V1.3.5 release might fix this issue, though it only kind of worked when on the machine I had temporary access to with 0365

**Comment by XtremeMaC** [comment]
@adb014 Hello, first up thanks for this what seems to be a great software for getting rid of LN :)
Anyways I've read the readme file and was disappointed to find that it won't work on O365, but tried my luck regardless :) 
As, I recently been migrated to O365 from LN, I had started looking for solutions before corp IT releases a software who knows when. (it'll take a while as there are thousands of employees globally). That Stellar software is stupidly expensive. IT migrated 60 days of emails/calendar/etc.

Anyway, your last comment peaked my interest and was wondering if v1.3.5 can be released anytime soon?

**Comment by adb014** [comment]
v1.3.5 is available on the release just not tagged as the latest version. It doesn't seem to fix the problems witth o365 however and so I'm tagging the o365 as "wontfix"

Sorry
D.
