### ISSUE TITLE
Error calling MIMEConvertCDParts(259)

### ISSUE THREAD

**Issue by luxifr** [adb014/nsf2x#9]
Hi,

tried to convert my mail NSF file but all I get is the error in the title for each and every mail. More specifically, when running in a Debugger I get these messages for the mails in question:

```
[2338:0002-3C88] 27.12.2017 14:54:07   CD to MIME error (Process: ? (00002338:00000002), Database: C:\mailconv\LocalMailbox.nsf, Note: 00000B42): File does not exist
[2338:0002-3C88] 27.12.2017 14:54:07   End CD to MIME Conversion(Process: ? (00002338:00000002), Database: C:\mailconv\LocalMailbox.nsf, Note: 00000B42)
```

Unfortunately I don't know enough about the Notes API to make any guess about the cause or what that actually means (as the file is there, of course)

If it helps: I've got a current Office 2016 from Office365 (64 Bit) and a 32 bit Notes 9.0.1 social edition. I'm working on a copy of my NSF file with notes running in the background and I set the "Always use external PST helper function" to "yes" according to your documentation.

What now? :)

Cheers

**Comment by adb014** [comment]
You don't get to the stage that the helper function is even called, as the error is in the NSF to EML conversion stage. The Lotus MIME conversion function is telling you the file "c:\mailconv\LocalMialbox.nsf" doesn't exist. Please check the existence and permissions on this file

D.

**Comment by adb014** [comment]
Closing as no feedback for several months
